/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Mon, Mar 07, 2011                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#include "iodefine.h"
#include "appli.h"
#include "machine.h"


void HardwareSetup(){
	
	int	i;

/*/////////////////////////////////
		IO ポート
//////////////////////////////////*/
	//	P10: TEST SW
	//  P11: SEL(リモコン）
	//  P12: CLK(リモコン）
	//  P14: 未使用
	//  P15: SW3
	//  P16: SW2
	//  P17: SW1
	IO.PCR1 = 0x06;
	IO.PUCR1.BYTE = 0xE1;
	
	
	// P20: SCK1
	// P21: RXD1
	// P22: TXD1
	// P23: CS3
	// P24: M_ENA
	IO.PCR2 = 0x1D;
	
	
	//	P30: LED1
	//	P31: LED2
	//	P32: LED3
	//	P33: LED4
	//	P34: MCW2
	//	P35: MCCW2
	//	P36: MCW3
	//	P37: MCCW3
	IO.PCR3 = 0xFF;
	IO.PDR3.BYTE = 0x0F;
	
	
	//	P50: MCW1
	//	P51: MCCW1
	//	P52: MCW4
	//	P53: MCCW4
	//	P54: DAT(リモコン）
	//	P55: CMD(リモコン）
	//	P56: SDA(EPROM)
	//	P57: SCL(EPROM)
	IO.PMR5.BYTE = 0x00;
	IO.PUCR5.BYTE = 0x00;
	IO.PCR5 = 0xEF;
	IO.PDR5.BYTE = 0x00;
	
	
	
	//	P60: 予備ポート
	//	P61:
	//	P62:
	//	P63:
	//	P64:
	//	P65:
	//	P66:
	//	P67:
	IO.PCR6 = 0x00;
	
	
	//  P70: CS4
	//  P71: RXD2
	//  P72: TXD2
	//  P74: CS1
	//	P75: CS2
	//	P76: Buzzer
	IO.PCR7 = 0x71;
	IO.PDR7.BYTE = 0x71;
	
	
	//	P85: 未使用
	//	P86:
	//	P87:
	IO.PCR8 = 0x00;
	
	

	
/*/////////////////////////////////
		A/D変換器
//////////////////////////////////*/

	//	ADCポート
	AD.ADCSR.BYTE = 0x77;	//	スキャンモード(AN4～AN7)


/******************************************************************
	各種タイマー設定
*******************************************************************/
	
	//WD->off
	WDT.TCSRWD.BYTE=0x92;
	WDT.TCSRWD.BYTE=0x92;
	WDT.TCSRWD.BIT.B4WI = 0;
	WDT.TCSRWD.BIT.TCSRWE=1;

	WDT.TCSRWD.BIT.B2WI=0;
	WDT.TCSRWD.BIT.WDON=0;
	
	WDT.TMWD.BYTE=0xFF;
	WDT.TCSRWD.BIT.B6WI = 1;
	WDT.TCSRWD.BIT.TCWE = 1;
	WDT.TCWD=0x00;
	
	for(i=0;i<4;i++)	MDIR[i] = 2;
	
	//10msecタイマー (10msec以上の周期にするとNG)
	TB1.TMB1.BYTE = 0xF8;		//	φ/8192でカウント(1800Hz)
	TB1.TLB1 = 76;				//	100msec周期
	
	//LED制御用タイマー(1ms周期のPWM、タイマーZ使用)
	TZ.TSTR.BYTE = 0x00;	//チャンネル0カウント動作
	TZ.TMDR.BYTE = 0x01;	//同期動作(TZ0, TZ1)
	TZ.TPMR.BYTE = 0x00;
	TZ.TFCR.BYTE = 0x00;
	TZ.TOER.BYTE = 0xFF;
	TZ.TOCR.BYTE = 0x00;
	
	TZ0.TCR.BYTE = 0xA0;	//	GRCでカウントクリア
	TZ0.TIORA.BYTE = 0x00;	//	コンペアマッチ出力禁止
	TZ0.TIORC.BYTE = 0x00;	//	コンペアマッチ出力禁止
	TZ0.TIER.BYTE = 0x07;	//	IMFA,B,Cで割込処理
	
	TZ0.GRA = 0x0000;		//	M1 Duty
	TZ0.GRB = 0x0000;		//	M2 Duty
	TZ0.GRC = 0x3999;		//	1msecクリア
	
	TZ1.TCR.BYTE = 0xE0;	//	同期クリア
	TZ1.TIORA.BYTE = 0x00;
	TZ1.TIORC.BYTE = 0x00;
	TZ1.TIER.BYTE = 0x03;
	
	TZ1.GRA = 0x0000;		//	M3 Duty
	TZ1.GRB = 0x0000;		//	M4 Duty
//	TZ1.GRC = 0x3999;
	
	
	IENR1.BIT.IENWP = 0;	//	ウェイクアップ割り込み禁止
	IENR1.BIT.IEN0 = 1;
	IENR2.BIT.IENTB1 = 1;	//	タイマーB1割込許可
	
	TZ.TSTR.BYTE = 0x03;	//	TZ0,1カウント動作
	
	//シリアル通信設定
	cpu_sci1_init();
	cpu_sci2_init();
}






void BuzzerSet(char pitch , char vol){
	
	TV.TCRV1.BYTE=0x01;
	TV.TCRV0.BYTE=0x10;
	TV.TCSRV.BYTE=0x06;
	
	TV.TCRV0.BIT.CKS=0;
	TV.TCORA=(char)((float)vol*((float)pitch/256.0));
	TV.TCORB=pitch;
}

void BuzzerStart(){
	TV.TCRV0.BIT.CKS=3;
}

void BuzzerStop(){
	TV.TCRV0.BIT.CKS=0;
}

