/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Mon, Jun 11, 2007                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
                  

#include	<machine.h>
#include 	"appli.h"
#include	"stacksct.h"

extern void main(void);
__entry(vect=0) void PowerON_Reset(void);

#pragma section ResetPRG

__entry(vect=0) void PowerON_Reset(void)
{ 
	 set_imask_ccr((UBYTE)1);
	_INITSCT();

	set_imask_ccr((UBYTE)0);

	main();
	
	sleep();
}
