/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Fri, Nov 07, 2008                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x100
