/***********************************************************************/
/*                                                                     */
/*  TDSN SH2 Board Sample Program                                      */
/*  DATE        :March 16, 2012                                        */
/*  CPU TYPE    :SH7083                                                */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
#include	"appli.h"
#include	"machine.h"
#include	"iodefine.h"


static const unsigned char CMD_read_data[] =				{0x01,0x42,0x00,0x00, 0x00,0x00,0x00,0x00, 0x00}; 
static const unsigned char CMD_read_data2[] =				{0x01,0x42,0x00,0x00, 0x00,0x00,0x00,0x00, 0x00,0x00,0x00,0x00,
															0x00,0x00,0x00,0x00, 0x00,0x00,0x00,0x00, 0x00};
static const unsigned char CMD_config_mode_enter[] =		{0x01,0x43,0x00,0x01, 0x00,0x00,0x00,0x00, 0x00};
static const unsigned char CMD_query_DS2_analog_mode[] =	{0x01,0x41,0x00,0x5a, 0x5a,0x5a,0x5a,0x5a, 0x5a};
static const unsigned char CMD_set_DS2_native_mode[] =		{0x01,0x4f,0x00,0xff, 0xff,0x03,0x00,0x00, 0x00};
static const unsigned char CMD_config_mode_exit2[] =		{0x01,0x43,0x00,0x00, 0x5a,0x5a,0x5a,0x5a, 0x5a};
static const unsigned char CMD_set_mode_and_lock[] =		{0x01,0x44,0x00,0x01, 0x03,0x00,0x00,0x00, 0x00};
static const unsigned char CMD_config_mode_exit[] =			{0x01,0x43,0x00,0x00, 0x00,0x00,0x00,0x00, 0x00};
static unsigned char	PADRD[30];
unsigned char			PS_DATA[10];
void	Ds2Com(const unsigned char * cmd, unsigned char txLen);


void updatePAD(){
	
	static unsigned char flag;
	int i;
	
	Ds2Com(CMD_read_data2,sizeof(CMD_read_data2));
	
	if(flag==2){
		Ds2Com(CMD_read_data,sizeof(CMD_read_data));
		for(i=0;i<100;i++);
		Ds2Com(CMD_read_data,sizeof(CMD_read_data));
	}
	else {
		Ds2Com(CMD_read_data2,sizeof(CMD_read_data2));
		for(i=0;i<100;i++);
		Ds2Com(CMD_read_data2,sizeof(CMD_read_data2));
	}
	for(i=0;i<100;i++);

	switch(PADRD[2]){
		case 0x5a:
			if(PADRD[1]==0x73){
				PS_DATA[0]=~PADRD[3];
				PS_DATA[1]=~PADRD[4];
				for(i=2;i<6;i++)	PS_DATA[i]=PADRD[3+i];
			}
			else if(PADRD[1]==0xF3){
				PS_DATA[0]=~PADRD[3];
				PS_DATA[1]=~PADRD[4];
				for(i=2;i<6;i++)	PS_DATA[i]=PADRD[3+i];
			}
			else{
				PS_DATA[0]=~PADRD[3];
				PS_DATA[1]=~PADRD[4];
				
				for(i=2;i<6;i++)	PS_DATA[i]=0x80;
				flag=PS_Set_AN();
			}
			break;
		
		default:
			for(i=0;i<2;i++)	PS_DATA[i]=0;
			for(i=2;i<6;i++)	PS_DATA[i]=0x80;
			break;
	}
}



unsigned char getPAD(unsigned char num){
	if(num <= PAD_AN_LY && num>= 0)		return(PS_DATA[num]);
	else								return(0);
}



unsigned char Ds2rw(const unsigned char *cmd){
	
	unsigned char TempCmd;
	unsigned char i,j,data,clk_cnt = 1;
	
	data=0;
	PS_CLK_raise;
	PS_CMD_raise;
	TempCmd = *cmd;
	
	for(j=0;j<5;j++);	//muda
	
	for(i=0;i<8;i++){
    	if((TempCmd & 0x01) == 0) /* CMDセット */
        	PS_CMD_fall;
    	else
        	PS_CMD_raise;
		
		TempCmd = TempCmd >> 1;
    	PS_CLK_fall;
    	
    	for(j=0;j<5;j++);	//muda
		
		if(PS_DAT!=0)	data+=clk_cnt;
		
		PS_CLK_raise;
    	clk_cnt *= 2;
	}
	
	 PS_CMD_raise;
  	
  	return(data);
}

//各コマンド送受信
void Ds2Com(const unsigned char * cmd,unsigned char txLen){
	
	unsigned char i,j;
	PS_SEL_fall;
	
	for(j=0;j<5;j++);	//muda
	for(i = 0; i < txLen;i++){
    	for(j=0;j<30;j++);	//muda
		PADRD[i]=Ds2rw(cmd+i);
	}
	
	PS_SEL_raise;
}


int PS_Set_AN(){
	
	int a,i;
	const unsigned char temp[4]={0xFF,0xFF,0x03,0x5A};
	
	a=0;
	
	Ds2Com(CMD_config_mode_enter,sizeof(CMD_config_mode_enter));
	for(i=0;i<200;i++);
	Ds2Com(CMD_query_DS2_analog_mode,sizeof(CMD_query_DS2_analog_mode));
	for(i=0;i<200;i++);
	
	for(i=0;i<4;i++){
		if(PADRD[i+3]!=temp[i])		a++;
	}
 	if(i==0){
		Ds2Com(CMD_set_DS2_native_mode,sizeof(CMD_set_DS2_native_mode));
		for(i=0;i<200;i++);
		Ds2Com(CMD_config_mode_exit2,sizeof(CMD_config_mode_exit2));
		return(2);
	}
	else if(a==4){
		Ds2Com(CMD_set_mode_and_lock,sizeof(CMD_set_mode_and_lock));
		for(i=0;i<200;i++);
		Ds2Com(CMD_config_mode_exit,sizeof(CMD_config_mode_exit));
		return(1);
	}
	return(0);
}

